<!DOCTYPE html>
<html>

<head>
    <title>Document</title>
</head>
<!-- Try-catch, throw, finally -->

<body>
    <script>
        // try-catch
        try {
            consoel.log("콘솔에 출력");
        } catch (error) {
            console.log(error.name);
            console.log(error.message);

        }
        // try구문에 감싸 놓으면 에러가 발생해도 멈추지 않고 이후의 연산을 진행


        var x = 0;
        var y = 3;
        console.log(x + y);

        try {
            if (x == 0) {
                throw "value is zero.";
            }
        } catch (error) {
            console.log(error);
        } finally {
            console.log("try/catch를 모두 실행한 후 반드시 실행하는 부분");
        }


        //throw -  throw를 설정하고 이에 해당할 경우 바로 catch로 이동됨
        //finally - try/catch를 모두 실행한 후 반드시 실행하는 부분
    </script>
</body>

</html>